### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 147

### ISSUE THREAD

**Issue by kinesivan** [lucy/tewi-font#22]
```
bdftopcf tewi-medium-11.bdf | gzip -9 > out/tewi-medium-11.pcf.gz
bdftopcf tewi-bold-11.bdf | gzip -9 > out/tewi-bold-11.pcf.gz
bdftopcf tewifw-medium-11.bdf | gzip -9 > out/tewifw-medium-11.pcf.gz
bdftopcf tewi2a-medium-11.bdf | gzip -9 > out/tewi2a-medium-11.pcf.gz
BDF Error on line 0: bad 'STARTFONT'
bdftopcf: bdf input, tewi2a-medium-11.bdf, corrupt
bdftopcf tewii-medium-11.bdf | gzip -9 > out/tewii-medium-11.pcf.gz
BDF Error on line 0: bad 'STARTFONT'
bdftopcf: bdf input, tewii-medium-11.bdf, corrupt
scripts/mkvar tewi2a-bold-11.bdf
Traceback (most recent call last):
  File "scripts/merge.py", line 30, in <module>
    lines = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 147: ordinal not in range(128)
Makefile:29: recipe for target 'tewi2a-bold-11.bdf' failed
make: *** [tewi2a-bold-11.bdf] Error 1

```

Trying to build the package on Arch Linux fails with this error.

**Comment by Foxtrot** [comment]
Bump, getting the same error on my Arch Install too

**Comment by lucy** [comment]
i can't reproduce this on gentoo :/

**Comment by lucy** [comment]
can you test with 69664bb98950dd6316ceb7e61a126cb0fcd99478?

**Comment by Foxtrot** [comment]
Hey lucy, I was able to install by compiling on an older machine (using the AUR) and then copying over the product .tar.xz, and it worked fine.

Regardless I just tested #69664bb and it works great, Thanks!

**Comment by lucy** [comment]
thanks for testing!
